version: "3.9"
services:
  mongo:
    build: ./databases/mongo-db
    container_name: fullstack-pilot-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: fullstack-pilot
    volumes:
      - mongo-data:/data/db

  apps-service:
    build: ./services/apps-service
    container_name: fullstack-pilot-apps-service
    environment:
      PORT: 4000
      MONGODB_URI: mongodb://mongo:27017/fullstack-pilot
    depends_on:
      - mongo
    ports:
      - "4000:4000"

  postgres:
    build: ./databases/postgre
    container_name: fullstack-pilot-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fullstack-pilot
      POSTGRES_USER: fullstack
      POSTGRES_PASSWORD: fullstack
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  services-service:
    build: ./services/services-service
    container_name: fullstack-pilot-services-service
    environment:
      PORT: 5000
      POSTGRES_DSN: postgres://fullstack:fullstack@postgres:5432/fullstack-pilot
    depends_on:
      - postgres
    ports:
      - "5000:5000"

  dependancies-service:
    build: ./services/dependancies-service
    container_name: fullstack-pilot-dependancies-service
    environment:
      ASPNETCORE_URLS: http://+:6060
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "6060:6060"

  client:
    build: ./client
    container_name: fullstack-pilot-client
    depends_on:
      - apps-service
    ports:
      - "5173:80"

volumes:
  mongo-data:
    driver: local
  postgres-data:
    driver: local
