apiVersion: v1
kind: Secret
metadata:
  name: services-service-secrets
  namespace: fullstack-pilot
type: Opaque
stringData:
  POSTGRES_DSN: postgres://fullstack:fullstack@postgres:5432/fullstack-pilot
