apiVersion: v1
kind: Service
metadata:
  name: fullstack-pilot-services-service
  namespace: fullstack-pilot
  labels:
    app: fullstack-pilot-services-service
spec:
  type: ClusterIP
  selector:
    app: fullstack-pilot-services-service
  ports:
    - port: 4002
      targetPort: 4002
      protocol: TCP
      name: http
