services:
  mongo:
    image: fullstack-pilot-mongo:latest
    build: .
    container_name: fullstack-pilot-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: fullstack-pilot
    volumes:
      - ./data:/data/db
      - ./init:/docker-entrypoint-initdb.d
