apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fullstack-pilot
  namespace: fullstack-pilot
spec:
  ingressClassName: nginx
  rules:
    - host: fullstack-pilot.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: fullstack-pilot-server
                port:
                  number: 4000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fullstack-pilot-client
                port:
                  number: 80
