apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fullstack-pilot
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/koydas/fullstack-pilot/client
    newTag: latest
