apiVersion: v1
kind: Service
metadata:
  name: fullstack-pilot-client
  namespace: fullstack-pilot
  labels:
    app: fullstack-pilot-client
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: fullstack-pilot-client
