apiVersion: v1
kind: Service
metadata:
  name: fullstack-pilot-server
  namespace: fullstack-pilot
  labels:
    app: fullstack-pilot-server
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 4000
      targetPort: 4000
  selector:
    app: fullstack-pilot-server
