apiVersion: v1
kind: Service
metadata:
  name: fullstack-pilot-dependancies-service
  namespace: fullstack-pilot
  labels:
    app: fullstack-pilot-dependancies-service
spec:
  type: ClusterIP
  selector:
    app: fullstack-pilot-dependancies-service
  ports:
    - port: 4003
      targetPort: 4003
      protocol: TCP
      name: http
