apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fullstack-pilot-services-service
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: fullstack-pilot
spec:
  project: default
  source:
    repoURL: https://github.com/koydas/fullstack-pilot.git
    targetRevision: main
    path: services/services-service/.devops
  destination:
    server: https://kubernetes.default.svc
    namespace: fullstack-pilot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5
